apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: prestashop
  name: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prestashop
  template:
    metadata:
      labels:
        app: prestashop
    spec:
      containers:
      - image: harbor.kakor.ovh/public/prestashop
        securityContext:
          allowPrivilegeEscalation: true
        env:
        - name: DB_SERVER
          value: {{ .Release.Name }}-mariadb
        - name: DB_USER
          value: prestashop
        - name: PS_INSTALL_AUTO
          value: "1"
        - name: DB_PASSWD
          valueFrom:
            secretKeyRef:
              name: password-mariadb
              key: password
        - name: DB_NAME
          value: prestashop
        {{- range $key, $val :=.Values.prestashop.env}}
        - name: {{ $key }}
          value: {{ $val | quote }}
        {{- end}}
        ports:
        - containerPort: 80
          protocol: TCP
        name: prestashop